### ISSUE TITLE
removing a task

### ISSUE THREAD

**Issue by zstarer** [capistrano/laravel#16]
hi -

anyone know how to disable the laravel:upload_dotenv_file step?  I've tried a few things inside the deploy.rb file with no luck.

it would be nice to be able to disable this so the .env file can persist between deploys to different environments.

**Comment by ikari7789** [comment]
You should be able to disable the upload of the .env file by overriding the "after 'deploy:symlink:shared', 'laravel:upload_dotenv_file'" task.

http://capistranorb.com/documentation/advanced-features/overriding-capistrano-tasks/

I don't have access to my projects right now, but in your deploy.rb, something like this may fix it?

```ruby
Rake::Task['laravel:upload_dotenv_file'].clear_actions
```

I'm personally of the camp where I don't feel the environment file should be shared between deploys. As values may change or be removed and doing so before deploy, while generating the new release directory, is the appropriate place to do so. Changing a single unified .env file between releases, there's no "safe" timing for when it should be updated without having affect to the either the new or old release.

**Comment by zstarer** [comment]
that did the trick. thank you!
