### ISSUE TITLE
Unable to run deploys with the latest version

### ISSUE THREAD

**Issue by ragingdave** [capistrano/laravel#17]
Not great at reading ruby but it seems something is amiss with version 0.0.3.

After running bundle install and fetching the 0.0.3 version of this, my cap builds have stopped with the error:

```
(Backtrace restricted to imported tasks)
cap aborted!
SystemStackError: stack level too deep

(See full trace by running task with --trace)
```

Upon adding `--trace`, the process freezes up and must be killed.

I have traced the issue back to this package, and even with a default cap file, the tasks will not load. In fact upon trying to run a `bundle exec cap install` in a completely empty folder, it fails until I remove or downgrade this package to 0.0.2

**Comment by ikari7789** [comment]
Which version of Capistrano are you using?
I'd like to help but there's not a ton of information to go on here.

**Comment by smotesko** [comment]
I just installed capistrano (v3.6.0) and laravel plugin and getting the same error:
```
$ bundle exec cap -T
(Backtrace restricted to imported tasks)
cap aborted!
SystemStackError: stack level too deep

Tasks: TOP => load:defaults
(See full trace by running task with --trace)
```

```
$ bundle exec cap -T --trace
cap aborted!
SystemStackError: stack level too deep
/Library/Ruby/Gems/2.0.0/gems/rake-11.2.2/lib/rake/task.rb:191
Tasks: TOP => load:defaults
```

**Comment by ikari7789** [comment]
Would it be possible to post your configuration?

**Comment by giacmir** [comment]
I have the same behaviour using capistrano 3.6.1.
Configuration is absolutely basic, all laravel options have been leaved as default. I only configured one environment with one single server.

**Comment by giacmir** [comment]
Update, using ruby 2.3.1 it works.

**Comment by christiancannata** [comment]
I get the same error with ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

**Comment by ikari7789** [comment]
Really not enough info in this issue for me to be able to help out. Please make a new ticket with more information if this continues to be a problem.
