### ISSUE TITLE
seed_db task is missing

### ISSUE THREAD

**Issue by chrisvanpatten** [capistrano/laravel#18]
The README lists a `laravel:seed_db` task, but it doesn't actually exist.

Easy to work around with the `laravel:artisan` command, but worth noting all the same.

**Comment by chrisvanpatten** [comment]
Happy to provide PR, but I wasn't sure if it was desired to have separate flag variables for the db:seed command, like for the db:migrate command.

**Comment by ikari7789** [comment]
I'm not necessarily against having a seed_db task, but I'm not really sure it's necessary. Migrations are something that will be run again and again over the course of an application's lifetime, whereas seeding is supposed to be used for "seeding" data into a database and usually only happens once, and in fact could even lead to more harm than good if accidentally run in a production environment.

**Comment by chrisvanpatten** [comment]
My main reason is for seeding in a staging or test environment, but I can understand the hesitation as well.

**Comment by ikari7789** [comment]
I'm updating the documentation to reflect the lack of seed_db. I think for the time being its best not to include it as an actual task. If you ever do need to seed the database, you can just use `laravel:artisan "seed:db"`.
