### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by nestormata** [capistrano/laravel#19]
Hi,
First, thanks for this Laravel Capistrano plugin.

I'm sure everyone has previous and extend knowledge on Capistrano so that they don't need any additional explanation on how to use this, but as I'm not really savy in Ruby I would appreciate a little bit more on guiding how to use it.
If anyone respond here I can make a pull request with the detailed information for the README file.

Here a few things I think would be great for those on Laravel that are new to Capistrano/Ruby:
- Where do we put the configuration variables?
- How do we tell Capistrano to actually run the Capistrano Laravel command? Like, what actually triggers all the Laravel setup.
- Should we previously have to create the database in the server?

Maybe, it would be great and easy to have an /example directory where you put a basic setup so we can look at it and understand.

Thanks for the great job.

**Comment by christianmarth** [comment]
@nestormata Capistrano is a deployment tool, not really designed for server provisioning so it's not going to create a Laravel app or database for you, This is more designed for deploying your code from your local dev environment to a staging or production server. 

Usually most of your configuration variables would live inside a `.env` file for things like your database credentials etc and then you set up some deployment variables inside the corresponding cap file for each environment, things like FTP details etc.

An example `deploy.rb` file with some explanations on usage would be great, I'll see if I can put something together after I've got it all working on my end.

**Comment by ikari7789** [comment]
Sorry for the delayed response. I'll try to improve the README this weekend. I understand there's probably a major lack of information about how to use this, and as its aimed at PHP Devs rather than those who are familiar with Ruby, it can be a little intimidating.

**Comment by nestormata** [comment]
Thanks @ikari7789 , really appreciate it.

@christianmarth I do know where the Laravel variables go. The current documentation assumes you already know many things about capistrano, that is all I'm saying and that it would be great to have at least a set of basic steps of how to set it up from scratch or even an example set up.

**Comment by ikari7789** [comment]
I've made a PR #23. Does this help make it a little easier for your to follow @nestormata? If so, I'll merge it in. If anything is still lacking, please let me know so that I can add it in.

**Comment by nestormata** [comment]
Looks great, thanks
