### ISSUE TITLE
Task not found?

### ISSUE THREAD

**Issue by mcblum** [capistrano/laravel#29]
I'm sure this is a stupid question... but any idea why this is throwing a `The deploy has failed with an error: Task "laravel:artisan[:artisan_task]" not found`?

```
set :artisan_task, 'view:clear'
after 'composer:run', 'laravel:artisan[:artisan_task]'
```

**Comment by ikari7789** [comment]
I think it's because it's interpreting :artisan_task as a string rather than as a symbol.
Try this:
```
artisan_task = 'view:clear'
after 'composer:run', "laravel:artisan[#{artisan_task}]"

**Comment by mcblum** [comment]
Interesting. When I try to run that task I get:
```
cap aborted!
ArgumentError: Task "laravel:artisan[view:clear]" not found

Tasks: TOP => composer:run
(See full trace by running task with --trace)
The deploy has failed with an error: Task "laravel:artisan[view:clear]" not found
```

My code is:

```

clear_view = 'view:clear'
after 'composer:run', "laravel:artisan[#{clear_view}]"

migrate = 'migrate'
after 'composer:run', "laravel:artisan[#{migrate}]"
```

Thanks for any guidance you can give!

**Comment by kekbait** [comment]
I managed to call the task with Rake, like this :

`Rake::Task["laravel:artisan"].invoke("view:clear")`

Hope this helped you !
