### ISSUE TITLE
Change the default shared_dir permissions?

### ISSUE THREAD

**Issue by ammezie** [capistrano/laravel#32]
Am wondering if there is a way to change the default shared_dir permissions to something like `775` ?

**Comment by ikari7789** [comment]
You can probably accomplish this with a custom capistrano task in your release setup.

Here's a simple example. I haven't tested this, it may need some tweaking.

`<project>/lib/capistrano/tasks/maintenance.rake`
```ruby
namespace :maintenance do
  desc "Set shared folder permissions"
  task :set_shared_folder_permissions do
    within release_path do
      execute :chmod, "0775", shared_path
    end
  end
end
```

Then you would include this task in your deploy.rb.
`<project>/config/deploy.rb`
```ruby
namespace :deploy do
  before :updated, "maintenance:set_shared_dir_permissions"
end
```
