### ISSUE TITLE
Why is migrations commented out?

### ISSUE THREAD

**Issue by allaire** [capistrano/laravel#4]
The migration task is commented out and not up to date. I currently have:

```ruby
namespace :deploy do
  task :migrate do
    invoke 'laravel:artisan', 'migrate'
  end
end
```

should it be updated with the code above?

**Comment by javierseixas** [comment]
Same to me. I guess something should be updated in the gems repository. The version 0.0.2 is too old: https://rubygems.org/gems/capistrano-laravel

**Comment by ragingdave** [comment]
Can the gem be updated already? The version still being distributed contains the commented out version of this code.

**Comment by ikari7789** [comment]
Sorry for the late response. I'll be helping maintain this plugin for the foreseeable future. If any of these issues are still persisting (all of the tickets are quite old), please let me know and I will do what I can to try and help fix things.

**Comment by mcblum** [comment]
@ikari7789 I ran into this issue today. I tried running ` invoke 'laravel:artisan', 'migrate'` and I got an error that it had already been invoked. Also when I use the build in migration method it says `Application in Production -- command cancelled`

**Comment by ikari7789** [comment]
@mcblum PR #20 should have fixed this. I'll release a minor version update shortly with the fix. Additionally, there is a `laravel:migrate_db` task which will run migrations.
