### ISSUE TITLE
Restrict laravel:optimize to laravel_version < 5.5

### ISSUE THREAD

**Issue by wunc** [capistrano/laravel#42]
Artisan optimize is deprecated in Laravel 5.5, so should probably not be automatically run as a part of a deploy for v5.5+. See https://laravel.com/docs/5.5/upgrade

**Comment by danielofficer** [comment]
Laravel 5.6 has removed this command entirely (https://laravel.com/docs/5.6/upgrade), so the deployment will fail:
```
01:22 laravel:artisan
      01 php artisan optimize --force --env=production
      01
      01
      01
      01   Command "optimize" is not defined.
      01
      01
      01
      01
(Backtrace restricted to imported tasks)
cap aborted!
```

Merging this would be greatly appreciated :)
