### ISSUE TITLE
acl paths and env file upload no longer working since upgrade

### ISSUE THREAD

**Issue by krtorio** [capistrano/laravel#45]
Hi,

I recently updated capistrano-laravel from 3.8.2 to 3.10.1

SSH and Git are working, but the env file uploading and acl paths are no longer working.
Found out about the env file issue because the app wont run because the env file is missing.
For the acl path I found out about it because the local storage path of the my app's latest release is not pointing to shared/storage/app but rather points to releases/<release number>/storage/app

below is the content of my deployment settings to the staging (and production server), copied from this github page:
set :laravel_version, 5.4
set :laravel_roles, :all
set :laravel_migration_roles, :all
set :laravel_upload_dotenv_file_on_deploy, true
set :laravel_dotenv_file, '../envfiles/.env.production'
set :laravel_server_user, 'centos'

set :laravel_ensure_linked_dirs_exist, true
set :laravel_set_linked_dirs, true
set :laravel_5_linked_dirs, [
  'storage'
]

set :laravel_set_acl_paths, true
set :laravel_ensure_acl_paths_exist, true
set :laravel_5_acl_paths, [
  'bootstrap/cache',
  'storage',
  'storage/fonts',
  'storage/app',
  'storage/app/public',
  'storage/framework',
  'storage/framework/cache',
  'storage/framework/sessions',
  'storage/framework/views',
  'storage/logs'
]

**Comment by ikari7789** [comment]
Hmmm, we've been using it with Capistrano 3.6.1. I'll give it a test with Capistrano 3.10.1.

**Comment by krtorio** [comment]
As a workaround I execute cp /path/to/env file to the current

For the acl path I haven't tried it but is that simply adding a symlink from the release's storage to the shared storage?

**Comment by ikari7789** [comment]
ACL paths is used to set the proper ACLs (i.e. if your web user is different from your deploy user, etc), using setfacl. If you don’t need that functionality there’s a flag to turn it off.

**Comment by ikari7789** [comment]
I haven't experienced any issues with Capistrano 3.10.1 in our environments. I'm going to close this ticket for now. If issues still persist, please re-open.
