### ISSUE TITLE
/usr/bin/env: 'setfacl': No such file or directory

### ISSUE THREAD

**Issue by jiangdi0924** [capistrano/laravel#48]
1. cap production deploy 

laravel version 5.5

then i get this error

  INFO [a4194d81] Running /usr/bin/env setfacl -Rn -m u:root:rwX -m u:root:rwX /home/rubyCapistrano/appserve1/releases/20180602051920/sto
rage as root@appserve.sphvip.com

 DEBUG [a4194d81] Command: /usr/bin/env setfacl -Rn -m u:root:rwX -m u:root:rwX /home/rubyCapistrano/appserve1/releases/20180602051920/st
orage

 DEBUG [a4194d81]       /usr/bin/env: 'setfacl': No such file or directory

**Comment by frankboris** [comment]
hello @jiangdi0924 i have the same error. Have you resolve this ?

**Comment by jiangdi0924** [comment]
@frankboris  in your server ,you need install acl , e.g.  my server is ubuntu  run` sudo apt-get install acl` then cap xxx deploy  is ok

**Comment by frankboris** [comment]
Thanks i don't have right to install app on server. To resolve this, i force capistrano to use **chmod**  command insted of **setfacl**

**Comment by mcblum** [comment]
@frankboris how did you do that?

**Comment by frankboris** [comment]
In my capistrano deploy.rb file, I add this lines:
`
namespace :laravel do

    desc "Setup Laravel folder permissions"
    task :permissions do
        on roles(:app), in: :sequence, wait: 2 do
            within release_path  do
                execute :chmod, "u+x artisan"
                execute :chmod, "-R 777 storage"
                execute :chmod, "-R 777 bootstrap/cache"
            end
        end
    end

end
`

**Comment by ikari7789** [comment]
If this is a feature unrequired by your deploy, you can disable it by setting the following config values:

```
# Ensure the paths in :file_permissions_paths exist?
set :laravel_ensure_acl_paths_exist, false

# Set ACLs for the paths in laravel_acl_paths?
set :laravel_set_acl_paths, false
```

**Comment by ikari7789** [comment]
@frankboris you should NEVER be setting permissions to `777` and I would never recommend it to someone who seems to be struggling with ACL issues. The folder should be writable by the web user and `644` should be more than enough.

**Comment by frankboris** [comment]
> @frankboris you should NEVER be setting permissions to `777` and I would never recommend it to someone who seems to be struggling with ACL issues. The folder should be writable by the web user and `644` should be more than enough.

Thks @ikari7789
