### ISSUE TITLE
Laravel Removed artisan optimize but this keeps running when we deploy using Laravel 6

### ISSUE THREAD

**Issue by wilecoyte78** [capistrano/laravel#58]
When we try to run it keeps running PHP aritsan optimize --force and we are on Larvel 6

Line 210

    desc 'Optimize the framework for better performance.'
    task :optimize do
        next if fetch(:laravel_version) >= 5.5

        Rake::Task['laravel:artisan'].invoke(:optimize, '--force')
    end

**Comment by wilecoyte78** [comment]
We had to comment out #after  'composer:run',    'laravel:optimize' from the laravel.rake.  Please fix as soon as possible.

**Comment by wilecoyte78** [comment]
What we found out the Configuration section does not say that it should go into the deploy.rb file

**Comment by ikari7789** [comment]
Are you properly specifying `:laravel_version` in your `config/deploy.rb` file? I just tested with a Laravel 7 project with `:laravel_version` set to `7` and it worked just fine.

**Comment by wilecoyte78** [comment]
If you read the comment above it did not say put in the deploy.rb file is why we had the issue and is now working fine.
